-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 10:25:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Charity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Charity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Charity` DEFAULT CHARACTER SET utf8 ;
USE `Charity` ;

-- -----------------------------------------------------
-- Table `Charity`.`Club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Charity`.`Club` (
  `IdClub` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `Mail` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdClub`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Charity`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Charity`.`Event` (
  `idEvent` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Place` VARCHAR(45) NOT NULL,
  `About` VARCHAR(250) NULL,
  `IdClub` INT NOT NULL,
  PRIMARY KEY (`idEvent`, `IdClub`),
  INDEX `fk_Event_Club_idx` (`IdClub` ASC) VISIBLE,
  CONSTRAINT `fk_Event_Club`
    FOREIGN KEY (`IdClub`)
    REFERENCES `Charity`.`Club` (`IdClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Charity`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Charity`.`Account` (
  `Password` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(20) NOT NULL,
  `LastName` VARCHAR(20) NOT NULL,
  `CIN` INT NOT NULL,
  `BloodType` VARCHAR(4) NULL,
  PRIMARY KEY (`CIN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Charity`.`Relations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Charity`.`Relations` (
  `idEvent` INT NOT NULL,
  `CIN` INT NOT NULL,
  INDEX `fk_Relations_Event1_idx` (`idEvent` ASC) VISIBLE,
  INDEX `fk_Relations_Account1_idx` (`CIN` ASC) VISIBLE,
  PRIMARY KEY (`idEvent`, `CIN`),
  CONSTRAINT `fk_Relations_Event1`
    FOREIGN KEY (`idEvent`)
    REFERENCES `Charity`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Relations_Account1`
    FOREIGN KEY (`CIN`)
    REFERENCES `Charity`.`Account` (`CIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
